### ISSUE TITLE
Put new noise API behind an "experimental" feature

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/noise-rs#120]

**Comment by Razaekel** [comment]
Putting the new API behind a experimental feature would require some way to hide their relevant examples in the cargo.toml behind the same feature flag, otherwise cargo test will fail because it tries to run the examples but can't find them if the flag is not enabled.

**Comment by amaranth** [comment]
The new noise API is now the only noise API so this is no longer relevant.
