### ISSUE TITLE
Figure out a better name for NoiseModule

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/noise-rs#121]

**Comment by Razaekel** [comment]
Suggested Names:

- Module
- NoiseModule (I prefer this, obviously)
- ModuleBase
- ValueSource ( I don't like this one because not all of the noisemodules will be sourcing values, most will be either modifying the value or modifying the point.)

**Comment by bjz** [comment]
- `NoiseGen`
- `NoiseFn`
- `GenFn`

In the future I see that these structs could simply implement `Fn(Input) -> Output`, but we need to wait for these to be stabilized first.

I also think that we need an impl for `Fn`.

**Comment by Razaekel** [comment]
Based off of the synonyms for module, here are other potential names:

- NoiseComponent
- NoiseUnit
- NoiseElement
