### ISSUE TITLE
Implement Transformer Modules

### ISSUE THREAD

**Issue by Razaekel** [brendanzab/noise-rs#128]
Need to Implement the following transformer modules:

- [ ] Displace
- [x] RotatePoint
- [x] ScalePoint
- [x] TransformPoint
- [x] Turbulence

**Comment by Razaekel** [comment]
Updated current status of the transformer modules.

I'm currently stumped on how to handle Displace, since it requires modifying the type of the member modules after initial construction, and rust isn't liking it.

You can see the current status of Displace [here](https://github.com/Razaekel/noise-rs/blob/feature/transformers/src/modules/transformers/displace.rs)

**Comment by brendanzab** [comment]
What error are you getting?

**Comment by Razaekel** [comment]
`error: mismatched types [--explain E0308]
  --> src/modules/transformers/displace.rs:49:9
49 |>         Displace {
   |>         ^ expected type parameter, found struct `modules::generators::constant::Constant`
note: expected type `modules::transformers::displace::Displace<Source, XDisplace, YDisplace, ZDisplace, UDisplace>`
note: found type `modules::transformers::displace::Displace<Source, modules::generators::constant::Constant<_>, modules::generators::constant::Constant<_>, modules::generators::constant::Constant<_>, modules::generators::constant::Constant<_>>``
