### ISSUE TITLE
Add Super Simplex noise

### ISSUE THREAD

**Issue by adudney** [brendanzab/noise-rs#161]
https://github.com/EversongMill/Genesis/blob/master/src/main/java/genesis/util/noise/SuperSimplexNoise.java

No blog post as of yet, but it's from the same author as Open Simplex noise. It looks fairly simple to implement, and it's always nice to have more noise functions.

As per https://www.reddit.com/r/proceduralgeneration/comments/68kpwt/most_important_algorithms_to_know/dhm8h81/?context=3 it has better results in higher dimensions.

**Comment by kelvin13** [comment]
Have you been able to make any sense of the formulas in that code? I’ve been trying to port it to Swift in [noise-swift](https://github.com/kelvin13/noise) and none of it makes sense…

**Comment by adudney** [comment]
Which ones specifically? Most of the algorithms are the same or very similar to Open Simplex, but with lookup tables instead of manual if statements.

**Comment by kelvin13** [comment]
@adudney for one, the stretch/squish factors are switched from the original, and I do not understand why he is sampling the vertices he is sampling. To transform a triangular lattice to rectangular coordinates, you need a skew constant of `0.5 * (1 / 3.squareRoot() - 1)`, but he is using the *unskew* constant `0.5 * (3.squareRoot() - 1)`

**Comment by kelvin13** [comment]
A word of warning, I benchmarked SuperSimplex this morning against OpenSimplex, and SuperSimplex appears to be about 65 percent slower than OpenSimplex, with full optimizations.

    generating a 1024 × 1024 2D noise texture with 12 octaves:
    OpenSimplex : 309139 μs
    SuperSimplex: 507195 μs

To keep things fair between the two, I added in the extra vertices for OpenSimplex. It appears the bulk of the slowdown comes from the vertex selection line

    let vertex_index:Int = region << 2 |
        Int(du0 - 0.5*dv0 + 1 - 0.5*Double(region)) << 3 |
        Int(dv0 - 0.5*du0 + 1 - 0.5*Double(region)) << 4

in my implementation, or 

    let index = (math::cast::<_, usize>(region_sum) << 2) |
    math::cast::<_, usize>(simplex_rel_coords[0] - simplex_rel_coords[1] / two + one - region_sum / two) << 3     
    | math::cast::<_, usize>(simplex_rel_coords[1] - simplex_rel_coords[0] / two + one - region_sum / two) << 4;

in yours.

I compiled with `-Ounchecked` so it’s not Swift being too careful and checking the array indices or anything.

**Comment by kelvin13** [comment]
update: It looks like SuperSimplex isn’t that slow, it’s just that OpenSimplex is easier for compilers to optimize. When inlining and constant folding are inhibited (in Swift, for example, by moving both inplementations into separate files from the main program), SuperSimplex and OpenSimplex are equally slow. Interesting.

**Comment by Razaekel** [comment]
You can implement it if you want to, just to provide another noise generator for people to use.

**Comment by kelvin13** [comment]
@Razaekel not sure if you’re @ me or adudney, but i’m not a rust developer, I’m working on a similar library [`noise`](https://github.com/kelvin13/noise) for the Swift language. My port might help though, as it has a functional implementation of 3D super simplex noise.
