### ISSUE TITLE
Propose using f64 instead of Float

### ISSUE THREAD

**Issue by Razaekel** [brendanzab/noise-rs#164]
I propose to use `f64` everywhere instead of the generic `Float` type. This would provide one immediate benefit in that all results could be expected to be the same, due to the required use of `f64`, instead of the possible use of either `f32` or `f64`, which could result in differences in the result due to floating point errors.

This would also simplify the API in that there would be no requirement to cast the result of the `get()` fn to `f32/f64`, and eliminate the need for the associated `Output` type, as the output for `get()` could now be `f64` everywhere.

**Comment by adudney** [comment]
The only downside I can see would be using this on platforms where f32 is still quite a bit faster (The only example I can think of would be GPUs, and Rust isn't super commonly used on GPUs at the moment, so I'm not sure this is even worth considering) This would require benchmarking however, as for the sake of API and accuracy f64 is way better, so if f32 provides no speed benefits on modern platforms then it should be thrown out.

I'm all for it, if only for simplifying the interface. In addition to the removal of a large portion of the float to float casting, it'll allow us to use `thing += x` as a small convenience over `thing = thing + x`.

**Comment by Razaekel** [comment]
Frankly, on GPUs it would be even faster to use SIMD-oriented operations and structures.

I did consider the possibility of using `noise-rs` on GPUs, but as it stands, the structure of the library doesn't really make it conducive to great performance on GPUs. That would be better done through a separate crate or sub-crate that specializes in GPU-based noise generation.

**Comment by adudney** [comment]
Very true. In that case I'm all for it.

**Comment by Razaekel** [comment]
Here's my general plan for the breakdown of applications:

1. This library, with f64 and providing accurate, reference implementations of procedural noise functions of every shape and form that can be implemented.

2. Either a sub-library crate or another library that provides SIMD implementations of noise functions that can be implemented using SIMD. SIMD provides registers of at least 128-bit and up to potentially 512-bits in AVX512.

3. Again, either a sub-library crate or another library that provides a reference GPU implementation, using f32.
