### ISSUE TITLE
Perlin is much smoother than expected

### ISSUE THREAD

**Issue by superdump** [brendanzab/noise-rs#187]
I'm looking at https://necessarydisorder.wordpress.com/2017/11/15/drawing-from-noise-and-then-making-animated-loopy-gifs-from-there/ and playing around with the Perlin implementation in noise-rs, trying to obtain similar results. However, all the results I get are locally very smooth as if there are no octaves. Is that correct / intended?

**Comment by superdump** [comment]
It looks like Processing specifically implements the superposition of noise with different octaves. The descriptions of some of the *Multi algorithms in noise-rs seem to be intended for doing that kind of combination but it's not clear how to take the Perlin noise generator and combine multiple octaves of it. How does one do that?

**Comment by Razaekel** [comment]
You could use the BasicMulti noise module, which implements a Perlin
Multifractal.

**Comment by superdump** [comment]
Perfect! I'd missed https://github.com/brendanzab/noise-rs/blob/0d43e1d68854a0c6cd4257e6ab4d75728bd75112/src/noise_fns/generators/fractals/basicmulti.rs#L67 😄 Thanks!
